### ISSUE TITLE
希望adapter有scratch link 一样的小图标

### ISSUE THREAD

**Issue by wwj718** [CodeLabClub/codelab_adapter_extensions#11]
[bilikyar](https://github.com/bilikyar)在微信中提到:

>  希望后面adapter跟scratch link一样的小图标最好，否则用户很难感觉到他的存在

我把我的思考贴过来， 用这个issue跟进这块的工作

>  小图标也在规划中，这块可能需要用到系统相关的库，我比较慎重，你可以提个issue，我们在那儿讨论细节，我已经做了一些工作在这块

**Comment by wwj718** [comment]
scratch link使用native方案，所以可以使用系统特性(小图标是系统特性)

如果要实现这个功能，有两个思路，其一是依赖于一个强大的UI库，来提供跨平台的支持。目前我在qt(pyqt5)中似乎没看到这个支持。

方案二是使用python包装过的系统库，如pywin32(Windows)、pyobjc(Mac)

目前我使用pyobjc完成在mac上的图标功能了。源码一时找不到，等我找到之前的实验代码，我贴过来。

**Comment by wwj718** [comment]
我找到之前的一些笔记

*  在mac下原生的NSStatusBar: [rumps](https://github.com/jaredks/rumps)
    *  using PyObjC 
        *  [demo](https://gist.github.com/yeonsh/9b084059c4eb48a730a9)
        *  [pyobjc_examples/](https://github.com/mjohnsullivan/pyobjc_examples/blob/master/main.py)
    *  https://stackoverflow.com/questions/10691222/nsstatusitem-in-python
    *  https://code-examples.net/en/q/22878 使用rumps包装pyobjc
```
from AppKit import NSStatusBar
status_item = NSStatusBar.systemStatusBar().statusItemWithLength_(-1) #NSVariableStatusItemLength
status_item.setImage_(<NSImage instance to status icon>)
```

**Comment by wwj718** [comment]
在windows下，这个功能名字叫`Tray Icon`, 在关键字的帮助下，Google到QT对其提供了支持！
![image](https://user-images.githubusercontent.com/3153878/57271384-da997580-70c1-11e9-8a8c-ac2ccbc604be.png)

https://doc.qt.io/archives/qt-4.8/qt-desktop-systray-example.html

**Comment by wwj718** [comment]
linux考虑 https://github.com/martinohanlon/shortcut  帮助启动

**Comment by bilikyar** [comment]
> scratch link使用native方案，所以可以使用系统特性(小图标是系统特性)
> 
> 如果要实现这个功能，有两个思路，其一是依赖于一个强大的UI库，来提供跨平台的支持。目前我在qt(pyqt5)中似乎没看到这个支持。
> 
> 方案二是使用python包装过的系统库，如pywin32(Windows)、pyobjc(Mac)
> 
> 目前我使用pyobjc完成在mac上的图标功能了。源码一时找不到，等我找到之前的实验代码，我贴过来。

用pyqt5 这个库加个小图标，挺简单的你看这个链接。 我感觉就这一次迁移框架的时候，就添加tray icon的代码就好了。
[链接](https://evileg.com/en/post/68/)

按道理，pyqt5 应该是跨平台的，我刚刚在windows，mac上测试过了上面链接里的代码，运行成功了。

**Comment by wwj718** [comment]
@bilikyar 太棒了

**Comment by wwj718** [comment]
@wangshub

**Comment by wangshub** [comment]
@wwj718 Copy，Pyqt5 做这个再好不过了 😋
