### ISSUE TITLE
重新设计codelab-adapter的样式

### ISSUE THREAD

**Issue by wwj718** [CodeLabClub/codelab_adapter_extensions#12]
![image](https://user-images.githubusercontent.com/3153878/57422417-8d90dd00-7242-11e9-9516-76c4960f1e42.png)

**Comment by wwj718** [comment]
[code-lab.sketch.zip](https://github.com/Scratch3Lab/codelab_adapter_extensions/files/3160134/code-lab.sketch.zip)

@wangshub  这是设计素材

**Comment by bilikyar** [comment]
希望大家看了之后，提多多的建议，帮助codelab-adapter的推进工作。

**Comment by wwj718** [comment]
https://adapter.codelab.club/user_guide/develop/ 测试版目前发布在这里

mac下目前基本正常。Window似乎存在兼容性问题，在 @wangshub 环境下布局正常，在我的测试环境下，存在布局问题。

**Comment by bilikyar** [comment]
我这边的windows10 64位测试过了，adapter可以跟scratch正常通讯，其中微信插件试了一试，没啥问题。
