### ISSUE TITLE
关于Scratch-VM里安装MQTT包时,webpack打包错误问题

### ISSUE THREAD

**Issue by bilikyar** [CodeLabClub/codelab_adapter_extensions#2]
由于最近adapter里内置了MQTT客户端,所以尝试在本地的Scratch-vm里安装了MQTT包,想尝试写一下Scratch和adapter的通讯[插件](https://scratch3.codelab.club/). 可在VM里`yarn run watch`的时候,就会报一下错误:
```
ERROR in ./node_modules/mqtt/mqtt.js
Module parse failed: Unexpected character '#' (1:0)
```
虽然这个并不会影响插件功能的正常运行,可我的强迫症对这种错误的发生是无法置之不理的,所以通过MQTT.js github 社区里面找到了[问题原因](https://github.com/mqttjs/MQTT.js/issues/720).
主要原因是,在 `./node_modules/mqtt/mqtt.js`里的`#!/usr/bin/env node`并不是有效的js代码,所以是无法被webpack打包程序所识别的. 
可行的[解决方案](https://github.com/mqttjs/MQTT.js/issues/720#issuecomment-444412404)是,在**webpack.config.js**里面添加如下代码:
```
var webpack = require("webpack");

const base = {
    // ... other webpack config ...
    plugins: [
        new webpack.NormalModuleReplacementPlugin(/^mqtt$/, "mqtt/dist/mqtt.js"),
    ],
};
```

这段代码告诉Webpack当看到`require（“mtqq”）`用`require（“mqtt / dist / mqtt.js”）`替换它，这是MQTT库的缩小版本，并且没有`#!`的开始。
[参考issue链接](https://github.com/mqttjs/MQTT.js/issues/720)
[参考wiki](https://zh.wikipedia.org/wiki/Shebang)

**Comment by wwj718** [comment]
@bilikyar 非常棒的提醒！
