### ISSUE TITLE
尝试使用树莓派来做硬件教学的探索--电源问题上的探讨

### ISSUE THREAD

**Issue by bilikyar** [CodeLabClub/codelab_adapter_extensions#3]
由于公司业务的原因，正在探索新形式的硬件课程，从半个月前跳入树莓派这个大坑后，就发现这个板子的内容极其丰富，所以，尝试把这个作为硬件课程的核心内容。可当在做移动小车的时候，就发现了问题，树莓派的供电比较麻烦，移动电源上方案还不完善，虽然网上各种技术帖子都说5v 2A的电源就够了，可今天用了充电宝的5v 2A电源接上树莓派，并且树莓派因此变砖之后，有点心凉，心疼我宝贝板子。
这里的最大的原因是，树莓派本身没有过电保护，而且，不像Arduino那样的单片机，需要规范的关机和开机过程才能保证寿命。 所以，直接用树莓派来做硬件课程的挑战性和难度，相对较大，还需要认真探索一段时间。

**Comment by zhouF96** [comment]
https://www.raspberrypi.org/documentation/hardware/raspberrypi/power/README.md
这边有详细说到树莓派的电源要求，根据原理图：
https://www.raspberrypi.org/documentation/hardware/raspberrypi/schematics/rpi_SCH_3b_1p2_reduced.pdf
3B的USB部分带有一个型号为MSMF250的自恢复保险丝，稳态电流最大2.5A，峰值电流最大5A

**Comment by bilikyar** [comment]
> https://www.raspberrypi.org/documentation/hardware/raspberrypi/power/README.md
> 这边有详细说到树莓派的电源要求，根据原理图：
> https://www.raspberrypi.org/documentation/hardware/raspberrypi/schematics/rpi_SCH_3b_1p2_reduced.pdf
> 3B的USB部分带有一个型号位MSMF250的自恢复保险丝，稳态电流最大2.5A，峰值电流最大5A



> https://www.raspberrypi.org/documentation/hardware/raspberrypi/power/README.md
> 这边有详细说到树莓派的电源要求，根据原理图：
> https://www.raspberrypi.org/documentation/hardware/raspberrypi/schematics/rpi_SCH_3b_1p2_reduced.pdf
> 3B的USB部分带有一个型号为MSMF250的自恢复保险丝，稳态电流最大2.5A，峰值电流最大5A

非常感谢你的回复，我的树莓派后面电源指示灯没问题，可sd卡读取指示灯完全不亮，跟客服联系之后，发现也有可能是充电宝充电过程中，突然断电的原因，这种时候，计算机出身的我，有点羡慕电子工程出身的孩子。
