### ISSUE TITLE
cmder下载后出问题，运行不成，文件坏了

### ISSUE THREAD

**Issue by Antifie** [CodeLabClub/codelab_adapter_extensions#32]
运行scratch-gui
我的开发环境为MacOS 10.13.5，确保你在本地按照了git和nodejs。
windows用户
有读者在邮件里反馈说，在Windows下遇到一些问题。我在Windows 10里做了测试，把注意事项补充进来。
安装nodejs.
使用cmder，而不是cmd。

**Comment by wwj718** [comment]
我在Windows 10下使用cmder倒是正常，使用的是最新版吗？

**Comment by Antifie** [comment]
C:\Scratch3>git clone https://github.com/LLK/scratch-gui
Cloning into 'scratch-gui'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (19/19), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
ffatal: the remote end hung up unexpectedly
atal: early EOF
fatal: index-pack failed

**Comment by Antifie** [comment]
为何下载安装会中断失败，error: RPC failed; curl 18 transfer closed with outstanding read data remaining？是哪里解压出了问题？cmder原网址软件出了问题，到国内网站下载无问题。

**Comment by wwj718** [comment]
看起来是网络问题，github的访问在国内时常不稳定

**Comment by Antifie** [comment]
error: RPC failed; curl 18 transfer closed with outstanding read data remaining？如何解决呢？

**Comment by wwj718** [comment]
搜索一下科学上网
