### ISSUE TITLE
关于树莓派插件

### ISSUE THREAD

**Issue by Steve0x2a** [CodeLabClub/codelab_adapter_extensions#36]
最新版本的codelab_adapter中似乎移除了树莓派插件 请问这个是基于什么考虑呢 还是用另外的插件替代了他的功能?

**Comment by Steve0x2a** [comment]
博客插件地址未更新 已找到新地址

**Comment by wwj718** [comment]
我近期准备发布codelab_adapter v2，有大量更新，对于编写extension会更为容易

**Comment by Steve0x2a** [comment]
> 我近期准备发布codelab_adapter v2，有大量更新，对于编写extension会更为容易

十分期待
