### ISSUE TITLE
除了EIM之外其他的scratch插件在哪能看到呢？

### ISSUE THREAD

**Issue by hyansuper** [CodeLabClub/codelab_adapter_extensions#38]
看了这篇文章https://codelab-adapter-docs.codelab.club/dev_guide/helloworld/
其中说插件需要两个部分：
1. scratch3.0网页中的插件(内应)
2. 在CodeLab Adapter中写一个插件，代理硬件设备、AI或其他程序

scratch端的插件(内应）示例我只找到了[EIM](https://github.com/Scratch3Lab/scratch3_eim)，请问其他的插件（比如Tello， Vector等)是开源的吗？
我本来是想看看怎么处理异步发送的消息如何等待它成功执行返回，比如下面的**伪代码**：
```
Scratch blocks:
<Vector drive_forward 100>
<Vector turn_left 90>
```
<drive_forward 100>代码块执行可能要几秒钟才返回，如何让它阻塞直到成功返回后在执行下一句呢？

另外请问codelab-adapter有开源吗？
谢谢！

**Comment by wwj718** [comment]
@hyansuper  
codelab-adapter的开源计划在这儿: https://www.codelab.club/blog/codelab-adapter-v2/

异步与同步的转化, 在EIM中有包含这部分:  https://github.com/Scratch3Lab/scratch3_eim/blob/v2/index.js#L290

我今天会写一个例子

Scratch相关的插件，在陆续开放出来，目前已经开放了几个: https://github.com/scratch3lab

**Comment by wwj718** [comment]
已更新相应文档： https://adapter.codelab.club/dev_guide/sync-message/

**Comment by hyansuper** [comment]
谢谢！
我目前采用的方案是用ROS当做中间节点，起到类似codelab adapter的作用，然后用roslaunch来启停extension 或server。我发现这个项目跟EIM的作用很类似https://github.com/Affonso-Gui/scratch3-ros-vm，这样更方便我接入自己的一些3d打印的机器人玩玩。

Ps 看了blog.just4fun，您真是太有才了！

**Comment by wwj718** [comment]
@hyansuper 谢谢鼓励，博客比较杂乱。

codelab adapter受ROS作者的《programming robots with ros》一书影响比较深，所以可以把它当作一个ROS的简易版使用，核心都是异步消息系统
