### ISSUE TITLE
更新codelab-adapter-mac-2_5_3之后使用cozmo插件出下面的提示

### ISSUE THREAD

**Issue by markbye** [CodeLabClub/codelab_adapter_extensions#41]
Command '['/usr/local/bin/python3.7', '/Users/maweifeng/codelab_adapter/servers/cozmo_server.py']' returned non-zero exit status 1.
连接不上cozmo，配置了 user_settings.py python3的 path；

**Comment by wwj718** [comment]
稍等 我来做个测试

**Comment by wwj718** [comment]
@markbye  刚更新了文档：http://adapter.codelab.club/extension_guide/cozmo/

建议先确保python3 [01_hello_world.py](https://github.com/anki/cozmo-python-sdk/blob/master/examples/tutorials/01_basics/01_hello_world.py)运行正常

此外刷新一下浏览器缓存

我在本地测试已经ok

**Comment by markbye** [comment]
python3 01_hello_world.py 可以正常运行；其他文件夹的demo都能运行，远程工具也可以运行；
你修改的link也错了，应该是 https://adapterv2.codelab.club/user_guide/install/

**Comment by wwj718** [comment]
@markbye  方便的 w1162025955

**Comment by markbye** [comment]
加了
