### ISSUE TITLE
Extension_vector

### ISSUE THREAD

**Issue by robindpw** [CodeLabClub/codelab_adapter_extensions#45]
Hey, @wwj718 

_Firstoff: if this is not the right place to ask this question feel free to redirect me._

I was following this tutorial: https://adapter.codelab.club/extension_guide/vector/
To enable vector programming by SCRATCH but I cant find the extension for it,
Also i saw that it is missing in the extensions_v3 folder, is it possible to add this feature? 

Thanks.

**Comment by wwj718** [comment]
hi @robindpw  [the Vector node](https://github.com/CodeLabClub/codelab_adapter_extensions/blob/master/nodes_v3/node_vector.py) was build into CodeLab Adapter.

![image](https://user-images.githubusercontent.com/3153878/86504633-8d13b800-bded-11ea-9986-9370acab9313.png)


Scratch:

![image](https://user-images.githubusercontent.com/3153878/86504644-a157b500-bded-11ea-88ac-01e825ebaa2c.png)

**Comment by robindpw** [comment]
Thanks, i successfully connected vector to scratch thx for the adapter.
