### ISSUE TITLE
Physical Blocks Scratch

### ISSUE THREAD

**Issue by fazerlab** [CodeLabClub/codelab_adapter_extensions#46]
Hi 
I couldn´t find the Scratch extension code for physical blocks.
Could you help me?
Thank you

https://adapter.codelab.club/extension_guide/physical_blocks/
https://github.com/CodeLabClub/codelab_adapter_extensions/blob/master/nodes_v3/node_physical_blocks2.py

**Comment by wwj718** [comment]
Physical Blocks Scratch extension has not been open source
