### ISSUE TITLE
Extension中執行到while循環來執行攝像頭數據讀取后，疑似綫程阻塞導致插件無法响應後面的eim消息， 請教有沒有什麽辦法可以解決？

### ISSUE THREAD

**Issue by JimEverest** [CodeLabClub/codelab_adapter_extensions#49]
正在開發一款Adapter Extension， 其中有一條command是利用while循環從opencv capture攝像頭的畫面數據。 問題是一旦執行到這段while指令， 這個extension下其他指令都無法工作了， 從scratch發過來的eim消息得不到响應，extension_message_handle 無法觸發（其他extension的消息可以正常地響應）。 不知是不是與run機制有關，又或者是while阻塞了當前extension綫程， 請教有沒有什麽方法可以解決這個問題？

**Comment by wwj718** [comment]
建议开发时写成 [node](https://adapter.codelab.club/dev_guide/Adapter-Node/)（node是独立进程）, 可参考： https://github.com/CodeLabClub/codelab_adapter_extensions/blob/master/nodes_v3/node_physical_blocks2.py

**Comment by JimEverest** [comment]
很受用，非常感謝。
