### ISSUE TITLE
请教下 本项目和下载版本的区别

### ISSUE THREAD

**Issue by Apokar** [CodeLabClub/codelab_adapter_extensions#51]
比对 项目的代码和下载版本的代码,结构差别挺大,zip版本是根据本项目拓展一些功能打包生成的吗
zip版本中除了增加的python环境以及一些依赖库以外
还有添加了以及其他什么吗?

**Comment by wwj718** [comment]
是的 当前目录只包含了插件部分，核心部分目前未开源
