### ISSUE TITLE
请求大师adapter连接Arduino不成功总显示none type object 

### ISSUE THREAD

**Issue by wwsongid** [CodeLabClub/codelab_adapter_extensions#55]
请问大师，我用codelab adapter连接Arduino，连接时总显示none type obkect has no attribute flush，请问大师这个怎解决

另外codelab adapter v3的版本到哪下载

**Comment by wwj718** [comment]
抱歉 Arduino 插件已经不维护了呢

**Comment by wwsongid** [comment]
感谢老师抽空回答我的问题，是这样的，我是准备执教一节公开课，是想用自己训练的人工智能模型控制小灯，前面只要用英荔ai训练就可以了，可到了连接Arduino这边就出现标题中所述的问题，一时半会儿又找不到合适的软件平台代替，请老师能帮忙解决这个问题吗？另外你电话是多少，我能电话你吗

**Comment by wwsongid** [comment]
老师非常感谢您能在项目解散的情况下回复我，因为要上课就在这个地方卡在这儿了，搞得我已经好几天没睡好了，请老师帮帮忙吧，起初我以为是Arduino里firmataexpress版本上传不配，后来全试过了还是显示nonetype错，理论上能把adapter和Arduino连起来课就完整了，请老师帮看看nonetype错出在哪儿呢，必答谢！！

**Comment by wwsongid** [comment]
我看你是写的文档是用的adapter v3，但在你们网站里又没找到这个版本，请问哪里能下载到历史版本，盼老师回复

**Comment by wwj718** [comment]
是否可以使用 microbit 替代 Arduino 呢？我们目前基本在使用microbit，所以 Arduino 插件目前基本被放弃了（处于不可用状态）

hi @wwsongid  是否方便把你的联系方式(如微信之类)发到我邮箱上 wuwenjie718@gmail.com，我稍后加您

**Comment by wwsongid** [comment]
老师你好，真的非常感谢你能抽空回复，其实倒不是我死心眼非要用scratch去连arduino。
我上课的内容是想制作一个用自己训练的机器学习模型去控制小台灯的开和关，所以这里面就涉及两个要解决的问题
（1）编程环境中要有机器学习功能模块，并且该模块要有做声音训练的机器学习模型，像kittenblock,mind+虽然里面有机器学习模块，但都没有训练声音的，只有图像训练、表情训练等。就这一方面其它平台就达不到要求，只有codelab scratch中的英荔ai训练能用。
（2）程序控制硬件kittenblock,mind+这两个平台说实话都能连arduino和mirobit,但这两个平台都没有（1）中的机器学习模块所以又不行，搞得我这从接到上课任务一直到现在都很闹心。

目前像我这种情况一是钻牛角codelab scratch去连arduino；二是codelab连mirobit,但能不能连上我还没试过，mirobit扩展模块里好像没有对引脚写，只有读1、2引脚的,这样就控制不了接外设的引脚。主要是机器学习这一块我就只能选codelab scratch，其它平台的scratch没有进行语音的机器学习训练，所以我感觉解决我这种情况最快的还是codelab adapter中的arduino扩展搞起来。老师请你帮帮我吧，我现在搞得焦头烂额，当然选其他平台要有机器学习训练声音并且能连硬件才行，用codelab连不上开发版。其实说句实话，codelab adapter理念真的不错，比scratch link适应性更强，几乎能通吃。

当时我看你的邮箱是gmail，不知道发了你是否能收到，所以就在github上留言了，我的联系方式是：
姓名：宋巍巍
手机：13814386558
微信：v_wwsong
***@***.***
微信搜我手机号也能加的，请老师帮忙，当然不会让老师白忙活。



在 2022-04-17 10:12:26，"wwj718" ***@***.***> 写道：

是否可以使用 microbit 替代 Arduino 呢？我们目前基本在使用microbit，所以插件目前基本被放弃了

hi @wwsongid 是否方便把你的联系方式(如微信之类)发到我邮箱上 ***@***.***，我稍后加您
