### ISSUE TITLE
老师，路过的好心人，能帮看看Arduino连接的nonetype错吗

### ISSUE THREAD

**Issue by wwsongid** [CodeLabClub/codelab_adapter_extensions#56]
首先感谢各位路过的老师能驻足。因为自己要上公开课，选了这个平台，其他平台没找到合适的。在用codelab adapter连Arduino总是出现nonetype object has no attribute flush，步骤都按帮助文档来的，但一直有。因为一时半会儿实在找不到合适的的平台，所以想请好心的程序员哥哥们帮看，必答谢。
![IMG_20220415_220002](https://user-images.githubusercontent.com/15751979/163684449-3625d674-c1c2-415c-9c92-9691c9dad9d2.jpg)

@wwj718 @hidaris @m102981 @bilikyar @wangshub

**Comment by wwj718** [comment]
hi @wwsongid  很抱歉 ，Arduino插件目前已经不维护了，如果你想在 Scratch 里使用 Arduino 可以试试 https://estea8968.github.io/osep_web_serial/app/

这是固件烧录页面 https://estea8968.github.io/osep_web_serial/app/static/burn_hex/
