### ISSUE TITLE
可以看到Extension和Node具体实现差异么

### ISSUE THREAD

**Issue by YanYeZhuHua** [CodeLabClub/codelab_adapter_extensions#58]
本仓库里面好像找不到Extension的定义

**Comment by wwj718** [comment]
Node 以独立 Python 进程启动， Extension 以线程的方式启动，使用 Node 拥有更高自由度。

https://adapter.codelab.club/dev_guide/Adapter-Node/ 里有一些解释

**Comment by YanYeZhuHua** [comment]
意思是Extension完全弃用了么，后面主推Node么

**Comment by wwj718** [comment]
是的 主要在用 Node
