### ISSUE TITLE
extension-usb-mircobit插件对应固件usbMicrobit新增功能请求

### ISSUE THREAD

**Issue by HelloPlanet** [CodeLabClub/codelab_adapter_extensions#6]
请求开放usbMicrobit相关资源，以便增加以下功能：

1. microbit与codelab-adapter握手，从codelab-adapter一侧确认microbit处于随时可以与Scratch3交互的状态（而不是仅仅检测连接到了硬件）

2. 集成一键烧入codelab-adapter microbit插件所对应的usbMicrobit固件的功能。

谢谢您的辛苦付出，以及无私分享。

**Comment by wwj718** [comment]
@HelloPlanet  好的，我这周把相应固件开放出来，放在firmware目录之下，欢迎改进它。

固件更新之后，我再close这个问题。

**Comment by wwj718** [comment]
@HelloPlanet  固件已经提交， 可以自行修改： https://github.com/Scratch3Lab/codelab_adapter_extensions/tree/master/firmware

**Comment by wwj718** [comment]
@zhouF96 [串口通信部分](https://github.com/Scratch3Lab/codelab_adapter_extensions/blob/master/firmware/usbMicrobit_for_adapter.py#L94)写得很草率(基本是拍脑袋)，如果有什么看着不爽的地方，欢迎修改它
