### ISSUE TITLE
关于 Codelab-Adapter 读写蓝牙设备的统一 Python 接口

### ISSUE THREAD

**Issue by wangshub** [CodeLabClub/codelab_adapter_extensions#9]
@wwj718 Hi，在 adapter 中，目前缺少统一的蓝牙 Python 接口来和智能硬件通信，并且存在MacOS/Linux/Windows 的兼容性问题，而 [PyQT5/Bluetooth](https://doc.qt.io/qt-5/qtbluetooth-index.html) 似乎能解决这个问题，我会尝试在 MacOS/Windows 上验证 [Pando](https://github.com/Scratch3Lab/codelab_adapter_extensions/blob/master/extension_leju_pando.py) ，结果会更新在本 Issue。

![image](https://user-images.githubusercontent.com/20924010/56331929-d237d400-61c0-11e9-885b-06ee8efd5530.png)

是否有什么更好的方案呢？

**Comment by wwj718** [comment]
@wangshub  我的想法和你相似。此前找了一圈，只看到 PyQT5/Bluetooth 的方案相对理想，目前我大体上已经完成了tkinter到pyqt5的迁移，构建通用的蓝牙服务是切换到pyqt5主要动机之一。不过之前一直在等Scratch Link的开放，准备对着源码实现兼容它的bt服务，这样就可以兼容官方所有功能。

![image](https://user-images.githubusercontent.com/3153878/56332445-f1cffc00-61c2-11e9-9d48-6d8234acef33.png)

目前ble（bt5）可能是未来智能硬件的主流，所以我比较关注ble这块的兼容性。考虑到国内比较多用户使用win7（尤其是学校），所以近期codelab有位志愿者在探索[pygatt](https://github.com/peplin/pygatt) + BLED 112的通用方案。

如果你对用pyqt5重构UI和通用蓝牙服务有兴趣，我们可以一起来推进这块。

**Comment by wangshub** [comment]
@wwj718 
非常感谢邀请，很乐意参与进来 ~

蓝牙的适配比较繁琐，是否会考虑暂时先兼容某款常见型号的蓝牙 USB Dongle ?

**Comment by wwj718** [comment]
@wangshub 
好啊，那我们20号会后如果有时间就细节做些谈论。
是的，蓝牙的适配比较繁琐。 目前倾向采用BLED 112这款USB Dongle。

**Comment by wangshub** [comment]
@wwj718 Nice! 20 线下号见
